import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { ClerkProvider } from "@clerk/nextjs";
import { Open_Sans, Sansita_Swashed } from 'next/font/google'
import { Header } from "@/components/common/header";
import { Footer } from "@/components/common/footer";

export const openSans = Open_Sans({ subsets: ['latin'] })
export const sansitaSwash = Sansita_Swashed({ subsets: ['latin'] })

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Consider adding more metadata here, like keywords or Open Graph tags
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha384-nqcTpC+Pf7TV3V93gKJ6i0Dhd4g+4EaUS5Btzf8DC3nYTCILfWqKx+yz7Gl06VeD"
          crossOrigin="anonymous"
        />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${openSans.className} antialiased`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
